apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # ArgoCD looks for Secrets with label argocd.argoproj.io/secret-type: repo-creds
    # This ExternalSecret creates that Secret from AWS Secrets Manager
spec:
  refreshInterval: 24h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: argocd-repo-creds
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds   # ArgoCD watches for this label
      data:
        # Template using values fetched from remoteRef below
        type: git
        url: https://github.com/ravinder77
        username: "{{ .username }}"
        password: "{{ .password }}"   # GitHub PAT or Deploy Key

  data:
    - secretKey: username
      remoteRef:
        key: vox/argocd/github-creds
        property: username

    - secretKey: password
      remoteRef:
        key: vox/argocd/github-creds
        property: token
