apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vox-workloads
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: vox
  source:
    repoURL: https://github.com/ravinder77/vox-gitops.git
    targetRevision: main
    path: argocd/workloads
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
