apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/vox-argocd-irsa-role
    eks.amazonaws.com/token-expiration: "86400"
    eks.amazonaws.com/audience: sts.amazonaws.com
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/component: security
    app.kubernetes.io/managed-by: argocd