---
- name: Prepare EKS nodes
  hosts: eks_nodes
  become: true
  tasks:
    - name: Ensure chrony is installed
      ansible.builtin.package:
        name: chrony
        state: present

    - name: Ensure chronyd is enabled
      ansible.builtin.service:
        name: chronyd
        enabled: true
        state: started
