apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default
  source:
    repoURL: https://github.com/ravinder77/vox-gitops.git
    targetRevision: main
    path: helm/backend
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true