apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-backend
  namespace: vox
  labels:
    app.kubernetes.io/component: security
    app.kubernetes.io/managed-by: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vox-backend
      app.kubernetes.io/instance: vox-backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
          matchLabels:
              app.kubernetes.io/name: vox-frontend
              app.kubernetes.io/instance: vox-frontend
      ports:
        - protocol: TCP
          port: 4000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-egress-to-backend
  namespace: vox
  labels:
    app.kubernetes.io/component: security
    app.kubernetes.io/managed-by: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vox-frontend
      app.kubernetes.io/instance: vox-frontend
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: vox-backend
              app.kubernetes.io/instance: vox-backend
      ports:
        - protocol: TCP
          port: 4000
