apiVersion: v1
kind: Service
metadata:
  name: {{ include "vox-frontend.fullname" . }}-stable
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vox-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "vox-frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vox-frontend.fullname" . }}-canary
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vox-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "vox-frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vox-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vox-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "vox-frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
