apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-lbc-gateway-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: vox
  source:
    repoURL: https://github.com/kubernetes-sigs/aws-load-balancer-controller.git
    targetRevision: v2.14.0
    path: config/crd/gateway
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
