apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vox-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # ArgoCD Image Updater: watch ECR for new image tags
    argocd-image-updater.argoproj.io/image-list: backend=AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/vox-backend
    argocd-image-updater.argoproj.io/backend.update-strategy: semver
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main

spec:
  project: vox

  source:
    repoURL: https://github.com/ravinder77/vox-gitops.git
    targetRevision: main
    path: helm/backend
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: vox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas    # managed by HPA
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas


  revisionHistoryLimit: 10
