apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    # Wave 1 — Kyverno CRDs must exist before any ClusterPolicy/Policy objects.
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: vox

  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 1.17.0   #  pin version
    helm:
      values: |
        admissionController:
          replicas: 2
        backgroundController:
          enabled: true
        cleanupController:
          enabled: true
        reportsController:
          enabled: true

        resources:
          limits:
            cpu: 500m
            memory: 512Mi

        config:
          excludeNamespaces:
            - kube-system
            - kube-public
            - argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true   # needed for CRD upgrades
