apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: vox

  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.37.6
    helm:
      releaseName: argo-rollouts
      values: |
        fullnameOverride: argo-rollouts
        
        installCRDs: true
        
        controller:
          replicas: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              namespace: monitoring
        
        dashboard:
          enabled: true
          service:
            type: ClusterIP
            port: 3100
        
        serviceAccount:
          create: true
          annotations: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true





