apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-security
    app.kubernetes.io/component: security
  annotations:
    argocd.argoproj.io/sync-wave: "-5"   # Sync before workloads
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: vox

  source:
    repoURL: https://github.com/ravinder77/vox-gitops.git
    targetRevision: main
    path: platform/security/irsa
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    # namespace intentionally omitted — manifests declare their own namespaces

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /metadata/annotations
        - /metadata/resourceVersion
