name: Validate Manifests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.30.3

      - name: Validate manifests
        run: bash scripts/validate-manifests.sh
